### ISSUE TITLE
undo & selection bug (in master)

### ISSUE THREAD

**Issue by epills** [DartDraw/DartDraw#15]
How to recreate bug:
1. create two rectangles
2. select the first one and then select the second one again
3. click undo
![screen shot 2017-10-01 at 11 26 02 am](https://user-images.githubusercontent.com/28147698/31056400-05c588be-a69f-11e7-86ea-8d6eeab66716.png)
![screen shot 2017-10-01 at 11 26 12 am](https://user-images.githubusercontent.com/28147698/31056401-09687eea-a69f-11e7-94eb-2276590bf0af.png)

**Comment by emmaoberstein** [comment]
closed with #17
